[package]
name = "rusty_balls"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.21.0"
cgmath = "0.18.0"
env_logger = "0.11.6"
log = "0.4.25"
pollster = "0.4.0"
rand = "0.9.0"
wgpu = "24.0.1"
wgpu_text = "0.9.2"
winit = "0.29.15"
