[package]
name = "rusty_balls"
version = "0.1.0"
edition = "2021"

[dependencies]
cgmath = "0.18.0"
console = "0.15.10"
env_logger = "0.11.6"
pollster = "0.4.0"
wgpu = "23.0.1"
wgpu_text = "0.9.2"
winit = "0.29.15"
